---
- name: Crear backup de /etc en la máquina remota
  hosts: all
  become: yes
  tasks:
    - name: Prueba de conexión
      ping:

    - name: Comprimir /etc en la máquina remota
      command: tar czf /tmp/etc_backup.tar.gz /etc

- name: Descargar el backup a la máquina local con IP en el nombre
  hosts: all
  vars:
    local_backup_dir: "/home/ubuntu/backups"
    ext: ".tar.gz"
  tasks:
    - name: Asegurar que la carpeta local de backups exista
      file:
        path: "{{ local_backup_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Definir nombre final del archivo con la IP
      set_fact:
        backup_filename: "{{ local_backup_dir }}/etc_backup_{{ machine_ip }}{{ ext }}"
      delegate_to: localhost

    - name: Copiar backup desde la máquina remota
      fetch:
        src: /tmp/etc_backup.tar.gz
        dest: "{{ backup_filename }}"
        flat: yes


- name: Limpiar archivo de backup temporal en la máquina remota
  hosts: all
  become: yes
  tasks:
    - name: Eliminar el archivo comprimido del remoto (limpieza)
      file:
        path: /tmp/etc_backup.tar.gz
        state: absent
