---
- name: Obtener espacio libre en C en máquinas Windows usando SSH
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: ssh
    ansible_shell_type: powershell
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Get free space on C drive
      win_command: powershell.exe Get-PSDrive C

      register: espacio_c

    - name: Mostrar resultado
      debug:
        var: espacio_c.stdout_lines
 
